### ISSUE TITLE
You have an error in your MySQL syntax

### ISSUE THREAD

**Issue by 4Cris** [Tutorialwork/ProfessionalBans-Reloaded#5]
[08:45:42] [main/ERROR]: Tue Apr 28 08:45:42 CEST 2020 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
[08:45:42] [main/INFO]: The connection with the MySQL database was successfully
[08:45:42] [main/ERROR]: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'IF NOT EXISTS AUTHSTATUS int(11)' at line 1
[08:45:42] [main/ERROR]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[08:45:42] [main/ERROR]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[08:45:42] [main/ERROR]: 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[08:45:42] [main/ERROR]: 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[08:45:42] [main/ERROR]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[08:45:42] [main/ERROR]: 	at com.mysql.jdbc.Util.getInstance(Util.java:408)
[08:45:42] [main/ERROR]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
[08:45:42] [main/ERROR]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3933)
[08:45:42] [main/ERROR]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869)
[08:45:42] [main/ERROR]: 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
[08:45:42] [main/ERROR]: 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2675)
[08:45:42] [main/ERROR]: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465)
[08:45:42] [main/ERROR]: 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1912)
[08:45:42] [main/ERROR]: 	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2133)
[08:45:42] [main/ERROR]: 	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2067)
[08:45:42] [main/ERROR]: 	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5175)
[08:45:42] [main/ERROR]: 	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2052)
[08:45:42] [main/ERROR]: 	at de.tutorialwork.professionalbans.main.Data.seedDatabase(Data.java:145)
[08:45:42] [main/ERROR]: 	at de.tutorialwork.professionalbans.main.Main.MySQL(Main.java:238)
[08:45:42] [main/ERROR]: 	at de.tutorialwork.professionalbans.main.Main.init(Main.java:63)
[08:45:42] [main/ERROR]: 	at de.tutorialwork.professionalbans.main.Main.onEnable(Main.java:44)
[08:45:42] [main/ERROR]: 	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:285)
[08:45:42] [main/ERROR]: 	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:288)
[08:45:42] [main/ERROR]: 	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
[08:45:42] [main/ERROR]: 	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
[08:45:42] [main/INFO]: []===================================[]
[08:45:42] [main/INFO]: ProfessionalBans Reloaded | Version: 2.9.1
[08:45:42] [main/INFO]: Developer: Tutorialwork
[08:45:42] [main/INFO]: YT Kanal: youtube.com/Tutorialwork
[08:45:42] [main/INFO]: []===================================[]
[08:45:42] [main/INFO]: Enabled plugin ProfessionalBans Reloaded version 2.9.1 by Tutorialwork

**Comment by Tutorialwork** [comment]
What MySQL version do you use?
